import { Project } from 'interface/project.interface';

const PROJECTS: Project[] = [
	{
		category: 'Web Application',
		descriptions: 'My personal web application built using Next.JS and ChakraUI',
		end_date: 'May 2023',
		github_url: 'https://github.com/tamagossi/tamagossi-portfolio',
		id: 9,
		is_personal_project: true,
		project_url: 'https://www.tamago.ssi',
		role: 'Front-End Engineer',
		start_date: 'January 2023',
		tech: ['NextJS', 'ChakraUI'],
		title: 'Tamagossi Portfolio Website',
	},
	{
		id: 0,
		title: 'Trevv',
		category: 'Mobile Application',
		descriptions: 'An Instagram-like apps to share a review of a place',
		end_date: 'Present',
		role: 'Mobile Engineer',
		start_date: 'January 2023',
		tech: ['React Native', 'Redux', 'Antd'],
		responsibilities: [
			'Fix bugs',
			'Help the team to create their v2 apps',
			'Create image/video taking page, and image/video processing page',
			'Create video trimmer feature',
			'Create video trimmer preview feature',
		],
	},
	{
		id: 1,
		title: 'Staffinc Jobs',
		category: 'Web Application',
		end_date: 'Present',
		is_featured: true,
		project_url: 'https://jobs.staffinc.co/',
		role: 'Front-End Engineer',
		start_date: 'June 2021',
		tech: ['NextJS', 'Zustand', 'Antd', 'React Query'],
		thumbnail: '/images/app-screenshots/staffinc-jobs-thumbnail.png',
		descriptions:
			'Staffinc jobs searching application to handle user who not already downloaded the Staffinc app but still want to looking and apply to a job',
		responsibilities: [
			'Develop the app from the scratch',
			'Improve some patterns used within the app to minimize error possibility',
			'Lead the unit test process',
			'Improve the codebase',
			'Migrate codebase from Javascript to Typescript',
			'Solve memory leak issue due to lack of state management library',
		],
	},
	{
		id: 2,
		title: 'Staffinc - Recruitment Portal',
		category: 'Web Application',
		end_date: 'Present',
		is_featured: true,
		project_url: 'https://jobs.staffinc.co/',
		role: 'Front-End Engineer',
		start_date: 'Apr 2020',
		tech: ['NextJS', 'Zustand', 'Antd', 'React Query'],
		thumbnail: '/images/app-screenshots/recruitment-portal-thumbnail.png',
		descriptions:
			'Staffinc portal application for client who want to create job post, searching for agent, attend interview process',
		responsibilities: [
			'Develop all features within the apps that meet timeline and acceptance criteria',
			'Refactor its folder structure and its code style to increase clarity and code cleanness',
			'Do unit testing',
			'Migrate codebase from Javascript to Typescript',
			'Migrate state library to use zustand',
		],
	},
	{
		id: 3,
		title: 'Staffinc Suite',
		category: 'Web Application',
		end_date: 'February 2022',
		project_url: 'https://client.staffincsuite.co/',
		role: 'Front-End Engineer',
		start_date: 'December 2021',
		tech: ['NextJS', 'Zustand', 'ChakraUI', 'React Query'],
		thumbnail: '/images/app-screenshots/staffinc/staffinc-suite/staffinc-suite-thumbnail.png',
		descriptions:
			'Staffinc suite seamless portal as a platform for client to login both to Recruitment Portal or Management Portal',
		responsibilities: [
			'Help the team build the website',
			'Help the FE team by giving direction when developing the apps',
			'Do unit testing',
			'Migrate codebase from Javascript to Typescript',
			'Migrate state library to use zustand',
		],
	},
	{
		id: 4,
		title: 'Praktisi Mengajar',
		category: 'Web Application',
		end_date: 'March 2023',
		is_featured: true,
		role: 'Front-End Engineer',
		start_date: 'December 2022',
		tech: ['NextJS', 'MUI', 'Typecript', 'Context', 'Zustand'],
		thumbnail: '/images/app-screenshots/praktisi-mengajar-thumbnail.png',
		descriptions:
			'Kampus Merdeka platform to manage all activity in `Praktisi Mengajar` process',

		responsibilities: [
			'Help the team to increase development velocity by creating new Front End code base for Kampus Medeka IT team ',
			'Help the team to create all menus for role `Praktisi` in this platform',
			'Help the team fix bugs, accomplish new incoming request',
		],
	},
	{
		id: 5,
		title: 'Staffinc - Recruitment Admin Portal',

		role: 'Front-End Engineer',
		category: 'Web Application',
		end_date: 'Present',
		start_date: 'Apr 2020',
		project_url: '',
		tech: ['NextJS', 'Mobx', 'Antd'],
		descriptions:
			'Staffinc portal application for admin who will review job post which create by client',
		responsibilities: [
			'Successfully develop all features within the apps that meet timeline and acceptance criteria',
			'Refactor its folder structure and its code style to increase clarity and code cleanness',
			'Do unit testing',
		],
	},
	{
		id: 6,
		title: 'Bisa CPNS',
		role: 'Front-End Engineer',
		category: 'Web Application',
		end_date: 'April 2021',
		start_date: 'August 2020',
		project_url: '',
		tech: ['ReactJS', 'Bootstrap', 'Redux'],
		descriptions: 'Web based learning platform of civil administration servant',
		responsibilities: [
			'Successfully help the team to migrate the current app to SPA application using React',
			'Successfully help the team to increase code quality',
		],
	},
	{
		id: 7,
		title: 'Mindful',
		role: 'Front-End Engineer',
		category: 'Web Application',
		end_date: 'Nov 2021',
		start_date: 'Nov 2020',
		project_url: '',
		tech: ['ReactJS', 'Material', 'Socket'],
		descriptions: 'Chat app I create requested by client from upwork',
		responsibilities: [
			'Successfully help the client to construct the UI from the design given',
			'Successfully help the client to integrate client-side app to the BE to create realtime chat app',
		],
	},
	{
		id: 8,
		title: '99 Concierge',
		thumbnail: '/images/app-screenshots/freelance/99/99-thumbnail.png',

		role: 'Front-End Engineer',
		category: 'Web Application',
		end_date: 'Apr 2022',
		start_date: 'Feb 2022',
		project_url: '',
		tech: ['ReactJS', 'Styled', 'Context', 'Typescript'],
		descriptions: '99 rumah123.com property website',
		responsibilities: ['Succesfully help the team to finish feature given'],
	},
];

export default PROJECTS;
